In [17]:
from fy_project.env import P2PEnergyTrading, P2PEnergyTradingAuction
from fy_project.agent import P2PTradingPolicy, P2PTradingPolicyAuction 
from fy_project.utils import print_size, to_torch

from ray.rllib.core.rl_module import RLModuleSpec, RLModule
import torch

import json
import numpy as np
from pathlib import Path

In [2]:
path = Path(r"C:\Users\Abhyuday Chauhan\projects\FY_project\src\config")

In [3]:
with open(path.joinpath("env_config.json")) as f:
    env_cfg = json.load(f)
agent_cfg = env_cfg['agent_cfg']

# Env w/o Auction test

In [25]:
env = P2PEnergyTrading(**env_cfg)
observation_space = env.observation_spaces['household_0']
action_space = env.action_spaces['household_0']

C:\Users\Abhyuday Chauhan\projects\FY_project\src\fy_project\IEX_data\iex_hourly_market.csv


c:\Users\Abhyuday Chauhan\.conda\envs\FY_project\Lib\site-packages\gymnasium\spaces\box.py:235: UserWarning: WARN: Box low's precision lowered by casting to float32, current low.dtype=float64
  gym.logger.warn(
c:\Users\Abhyuday Chauhan\.conda\envs\FY_project\Lib\site-packages\gymnasium\spaces\box.py:305: UserWarning: WARN: Box high's precision lowered by casting to float32, current high.dtype=float64
  gym.logger.warn(


In [65]:
obs, info = env.reset()
observation_space.contains(obs['household_0'])

2025-08-03 00:00:00


True

In [66]:
action = {"household_0" : np.random.random(size=(24,)).astype(dtype=np.float32)}

In [67]:
action_space.contains(action['household_0'])

True

In [68]:
obs, rewards, terminated, _, _ = env.step(action)

In [69]:
env.observation_spaces['household_0'].contains(obs['household_0'])

True

In [70]:
model_spec = RLModuleSpec(
        module_class=P2PTradingPolicy, 
        model_config=agent_cfg,
        observation_space=observation_space,
        action_space=action_space
    )

policy = model_spec.build()

In [76]:
test_input = {
    "market_price": torch.rand(24),
    "battery_soc": torch.rand(1),
    "battery_capacity"  : torch.rand(1),
    "forecast_demand": torch.rand(24),
    "generation": torch.rand(24)
}

In [77]:
outputs = policy.forward_inference(test_input)

In [78]:
outputs['action_dist_inputs']

tensor([-0.0649,  0.0772,  0.0350, -0.0385, -0.0676,  0.1342, -0.0199,  0.0126,
        -0.1096, -0.0649,  0.0733, -0.1074, -0.0810,  0.0387,  0.0215,  0.0688,
         0.0475, -0.0090,  0.0413,  0.0203,  0.0651, -0.1094,  0.0248,  0.0891])

In [80]:
val=policy.compute_values(test_input)
val, val.shape

(tensor([0.0900], grad_fn=<ViewBackward0>), torch.Size([1]))

In [83]:
action_space.contains(outputs['action_dist_inputs'].numpy())

True

# Env w Auction Test

In [4]:
env = P2PEnergyTradingAuction(**env_cfg)
observation_space = env.observation_spaces['household_0']
action_space = env.action_spaces['household_0']

C:\Users\Abhyuday Chauhan\projects\FY_project\src\fy_project\IEX_data\iex_daily_market.csv


c:\Users\Abhyuday Chauhan\.conda\envs\FY_project\Lib\site-packages\gymnasium\spaces\box.py:235: UserWarning: WARN: Box low's precision lowered by casting to float32, current low.dtype=float64
  gym.logger.warn(
c:\Users\Abhyuday Chauhan\.conda\envs\FY_project\Lib\site-packages\gymnasium\spaces\box.py:305: UserWarning: WARN: Box high's precision lowered by casting to float32, current high.dtype=float64
  gym.logger.warn(


In [5]:
obs, info = env.reset()
observation_space.contains(obs['household_0'])

2024-11-20 00:00:00


True

In [8]:
action = {"household_0" : np.random.random(size=(48,)).astype(dtype=np.float32)}
action_space.contains(action['household_0'])

True

In [9]:
obs, rewards, terminated, _, _ = env.step(action)

In [12]:
env.observation_spaces['household_0'].contains(obs['household_0'])

True

In [16]:
model_spec = RLModuleSpec(
        module_class=P2PTradingPolicyAuction, 
        model_config=agent_cfg,
        observation_space=observation_space,
        action_space=action_space
    )

policy = model_spec.build()

In [18]:
test_input = {
    "market_price": torch.rand(24),
    "battery_soc": torch.rand(1),
    "battery_capacity"  : torch.rand(1),
    "forecast_demand": torch.rand(24),
    "generation": torch.rand(24)
}

In [19]:
outputs = policy.forward_inference(test_input)

In [22]:
outputs['action_dist_inputs']

tensor([ 0.0144, -0.0809,  0.0333,  0.0104,  0.1188, -0.1319, -0.0324,  0.0477,
         0.0013, -0.1112,  0.0443, -0.0307,  0.1183, -0.1582,  0.0398,  0.0607,
         0.0110,  0.1648, -0.0500,  0.0717, -0.0270,  0.0602,  0.0748, -0.0846,
         0.5247,  0.4902,  0.4697,  0.4745,  0.5222,  0.5189,  0.4590,  0.5180,
         0.5094,  0.4827,  0.4840,  0.4748,  0.5349,  0.5184,  0.5067,  0.5180,
         0.4659,  0.5189,  0.5188,  0.4757,  0.4859,  0.5034,  0.4951,  0.5036,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000])

In [23]:
val=policy.compute_values(test_input)
val, val.shape

(tensor([0.0534], grad_fn=<ViewBackward0>), torch.Size([1]))

In [25]:
action_space.contains(outputs['action_dist_inputs'][:48].numpy())

True