In [1]:
import numpy as np
import pandas as pd

In [2]:
t=np.random.rand(10)

In [3]:
t

array([0.74932479, 0.16578152, 0.20027554, 0.82038843, 0.97073263,
       0.19412208, 0.87139677, 0.39197817, 0.96243658, 0.00392067])

In [4]:
t.sum()

np.float64(5.330357183659412)

In [20]:
a=np.random.rand(10)
b= np.random.rand(10)
c= np.random.rand(10)

In [21]:
a[1] = np.nan

In [22]:
a, b,c

(array([0.05904743,        nan, 0.4832743 , 0.743232  , 0.1083384 ,
        0.83154775, 0.77003319, 0.548026  , 0.83011344, 0.35223795]),
 array([0.09343297, 0.39719239, 0.8851527 , 0.01910485, 0.9804841 ,
        0.90519336, 0.4387639 , 0.43506874, 0.2039471 , 0.35124955]),
 array([0.2278964 , 0.99631356, 0.29787941, 0.11399524, 0.99043656,
        0.49220528, 0.3645774 , 0.06261317, 0.78043728, 0.77427694]))

In [17]:
np.where(a > 0.5, b*c, 0)

array([0.1554831 , 0.        , 0.11629072, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.54764998, 0.18976146])

In [24]:
if np.isnan(a):
    print("a is NaN or None")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [26]:
if np.isnan(a).sum()>0:
    print("a has NaN values")

a has NaN values


In [27]:

from ray.rllib.examples.envs.classes.multi_agent import MultiAgentCartPole