In [2]:
import numpy as np
from datetime import datetime, timedelta

In [3]:
a=datetime(2024, 3, 1)

In [4]:
a.timetuple().tm_yday

61

In [5]:
a=np.random.random(10)*2-1

In [11]:
a

array([-0.15413076,  0.18574421, -0.67881361,  0.29739748, -0.49076537,
        0.84969444,  0.00139125, -0.21055702, -0.5678775 ,  0.83508484])

In [ ]:
np.sum(np.abs(((a>0)*0.8+(a<0)*1.5)*a))

array([-0.23119614,  0.14859536, -1.01822042,  0.23791798, -0.73614805,
        0.67975556,  0.001113  , -0.31583553, -0.85181625,  0.66806787])

In [18]:
import pandas as pd

In [19]:
df = pd.read_csv(r"C:\Users\Abhyuday Chauhan\projects\FY_project\src\fy_project\IEX_data\iex_15min_market.csv")

In [22]:
df["price"].mean()

np.float64(4289.621258977429)

In [7]:
a

array([-0.61423288, -0.9790135 , -0.12033465, -0.1532551 ,  0.51465488,
       -0.38485166, -0.32877994, -0.38939295, -0.75610512,  0.16629571])

In [6]:
np.where(a<0, 1.5*a, 0.8*a)

array([-0.92134932, -1.46852025, -0.18050197, -0.22988265,  0.4117239 ,
       -0.57727749, -0.49316991, -0.58408942, -1.13415769,  0.13303657])